### ISSUE TITLE
Responsive styles - navigation

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Announcements-Django#10]
- Collapsed nav styles need to be updated to match the latest main site styles
- Links should be white on hover, not gold
- Collapse button is not positioned correctly and overlaps/is not accessible in some cases
![screen shot 2017-09-28 at 9 22 02 am](https://user-images.githubusercontent.com/1649216/30971762-8400f8bc-a42e-11e7-80fb-226f4c6bda63.png)
- Font size should be reduced slightly at -lg breakpoint so that all links fit within a single line (see main site styles)
![screen shot 2017-09-28 at 9 22 48 am](https://user-images.githubusercontent.com/1649216/30971815-a6caab36-a42e-11e7-9ffb-068d62373d84.png)

**Comment by jmbarne3** [comment]
Closed by #13
