### ISSUE TITLE
Responsive styles - frontend announcement list

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Announcements-Django#11]
- Main site navigation needs some extra breathing room between it and the Announcements h1.  We've got main site v3 set up to use a dark gray navbar on pages without a header image--will post a link in Slack
- Consider breaking out of the masonry layout at the -md breakpoint and below for announcement card contents to not clip out of their containers
![screen shot 2017-09-28 at 9 24 30 am](https://user-images.githubusercontent.com/1649216/30972178-6ff4021e-a42f-11e7-8c27-a83ea9d74b43.png)
- Consider using a smaller font size for the Ongoing Announcements heading; make sure it does not cause horizontal scrollbars at smaller screen sizes
- Consider removing the "Learn More" buttons on each announcement card with a link wrapped around each announcement title
- Consider using a smaller font size for announcement titles, and possibly for audience and contact info

**Comment by jmbarne3** [comment]
Closed by #13
