### ISSUE TITLE
Date fields on announcement create/update form have no native or custom datepicker

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Announcements-Django#35]
Looks like the date fields on the announcement create/update view were intended to be used with a datepicker javascript lib (see https://github.com/UCF/UCF-Announcements-Django/blob/master/src/js/backend-script.js#L26-L35), but datepickers don't seem to initialize.

Tested in latest Chrome, FF

**Comment by jmbarne3** [comment]
Fixed by #36
