### ISSUE TITLE
Superusers have the ability to set the post status of a new announcement to 'publish', but it does not take effect

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Announcements-Django#8]
Because superusers have access to modify the post status of an announcement on both the create and update forms, a superuser could set the post status of a new announcement to 'publish', but it won't take effect since all new announcements are saved as 'pending'.

The create form should either allow superusers specifically to bypass the forced pending status for new events, or the option to modify the status should be removed.

**Comment by jmbarne3** [comment]
Fixed by #6
